// import type { Metadata } from "next";
import { Manrope } from "next/font/google";
import "./globals.css";
import Footer from "./components/Footer";
import Header from "./components/Header"

const manrope = Manrope({
  variable: "--font-manrope-sans",
  subsets: ["latin"],
});

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">

      <body

        className={`${manrope.variable} antialiased`}
        id="__next"
      >
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
